import React from 'react';
import { Link } from 'react-router-dom';
import { Rocket, Compass, Sparkles, ShieldCheck, TrendingUp, BarChart3 } from 'lucide-react';

export default function HomeHub() {
  return (
    <div className="w-full max-w-5xl mx-auto py-12 px-4 md:px-0">
      {/* Hero Section */}
      <div className="text-center space-y-4 mb-12">
        <div className="inline-flex items-center space-x-1.5 px-3 py-1 bg-indigo-50 border border-indigo-100 rounded-full text-indigo-600 text-xs font-bold uppercase tracking-wider animate-pulse">
          <Sparkles className="w-3.5 h-3.5" />
          <span>Next-Gen Fundraising</span>
        </div>
        <h2 className="text-4xl md:text-5xl font-black tracking-tight text-slate-100 font-display max-w-3xl mx-auto leading-tight">
          Venture-Grade Profiles,<br />
          <span className="bg-gradient-to-r from-indigo-600 via-indigo-500 to-cyan-500 bg-clip-text text-transparent">
            Generated by AI
          </span>
        </h2>
        <p className="text-base text-slate-400 max-w-2xl mx-auto font-medium leading-relaxed">
          BlackWhale transforms raw startup metrics into investor-ready profiles in minutes. 
          Empowering founders with automated pitch storytelling and helping investors screen deals at scale.
        </p>
      </div>

      {/* Selector Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-16">
        {/* Founder Pathway */}
        <div className="glass-panel glass-panel-hover rounded-3xl p-8 shadow-md relative overflow-hidden flex flex-col justify-between min-h-[340px]">
          <div className="absolute -right-16 -top-16 w-48 h-48 bg-indigo-500/5 rounded-full blur-2xl pointer-events-none"></div>
          
          <div className="space-y-4">
            <div className="w-12 h-12 rounded-2xl bg-indigo-50 flex items-center justify-center border border-indigo-100 text-indigo-600 shadow-sm">
              <Rocket className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-slate-100 font-display">
              For Startup Founders
            </h3>
            <p className="text-sm text-slate-400 leading-relaxed">
              Create an investor-ready startup profile. Fill in raw product stats, let the AI generate professional pitch copy, calculate scorecards, and publish directly to VCs.
            </p>
            <ul className="space-y-2 text-xs text-slate-500 font-medium">
              <li className="flex items-center space-x-2">
                <ShieldCheck className="w-4 h-4 text-indigo-500" />
                <span>Automated pitch generation</span>
              </li>
              <li className="flex items-center space-x-2">
                <ShieldCheck className="w-4 h-4 text-indigo-500" />
                <span>Algorithmic readiness scorecards</span>
              </li>
              <li className="flex items-center space-x-2">
                <ShieldCheck className="w-4 h-4 text-indigo-500" />
                <span>Upload pitch decks & media</span>
              </li>
            </ul>
          </div>
          
          <div className="mt-8">
            <Link
              to="/founder/onboarding"
              className="w-full inline-flex items-center justify-center space-x-2 px-6 py-3.5 bg-gradient-to-r from-indigo-600 to-indigo-700 hover:brightness-110 text-white text-sm font-extrabold tracking-wider uppercase rounded-2xl shadow-lg shadow-indigo-600/15 transition-all duration-300"
            >
              <span>Enter Founder Workspace</span>
              <Rocket className="w-4 h-4" />
            </Link>
          </div>
        </div>

        {/* Investor Pathway */}
        <div className="glass-panel glass-panel-hover rounded-3xl p-8 shadow-md relative overflow-hidden flex flex-col justify-between min-h-[340px]">
          <div className="absolute -right-16 -top-16 w-48 h-48 bg-cyan-500/5 rounded-full blur-2xl pointer-events-none"></div>
          
          <div className="space-y-4">
            <div className="w-12 h-12 rounded-2xl bg-cyan-50 flex items-center justify-center border border-cyan-100 text-cyan-600 shadow-sm">
              <Compass className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-slate-100 font-display">
              For Venture Investors
            </h3>
            <p className="text-sm text-slate-400 leading-relaxed">
              Browse, screen, and filter emerging startups. Apply sliders to evaluate market potential, target raise size, and average benchmark scores. Contact founders directly.
            </p>
            <ul className="space-y-2 text-xs text-slate-500 font-medium">
              <li className="flex items-center space-x-2">
                <ShieldCheck className="w-4 h-4 text-cyan-500" />
                <span>Multi-metric filters & search</span>
              </li>
              <li className="flex items-center space-x-2">
                <ShieldCheck className="w-4 h-4 text-cyan-500" />
                <span>Detailed scorecard breakdown</span>
              </li>
              <li className="flex items-center space-x-2">
                <ShieldCheck className="w-4 h-4 text-cyan-500" />
                <span>1-Click direct meeting requests</span>
              </li>
            </ul>
          </div>
          
          <div className="mt-8">
            <Link
              to="/investor/directory"
              className="w-full inline-flex items-center justify-center space-x-2 px-6 py-3.5 bg-gradient-to-r from-cyan-600 to-cyan-700 hover:brightness-110 text-white text-sm font-extrabold tracking-wider uppercase rounded-2xl shadow-lg shadow-cyan-600/15 transition-all duration-300"
            >
              <span>Explore Deal Directory</span>
              <Compass className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </div>

      {/* Mock Profile Pathway */}
      <div className="flex justify-center mb-16">
        <Link
          to="/mock"
          className="inline-flex items-center justify-center space-x-2 px-8 py-4 bg-gradient-to-r from-emerald-600 to-teal-600 hover:brightness-110 text-white text-sm font-extrabold tracking-wider uppercase rounded-2xl shadow-lg shadow-emerald-600/15 transition-all duration-300"
        >
          <Sparkles className="w-5 h-5" />
          <span>View Full End-Output Profile Mock</span>
        </Link>
      </div>

      {/* Platform Statistics */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 text-center border-t border-slate-700/40 pt-10">
        <div className="space-y-1">
          <div className="flex items-center justify-center space-x-1.5 text-slate-500 font-bold uppercase tracking-wider text-[11px]">
            <TrendingUp className="w-4 h-4 text-indigo-500" />
            <span>Matched Capital</span>
          </div>
          <p className="text-3xl font-black text-slate-100 font-display">$12,450,000</p>
        </div>
        <div className="space-y-1">
          <div className="flex items-center justify-center space-x-1.5 text-slate-500 font-bold uppercase tracking-wider text-[11px]">
            <BarChart3 className="w-4 h-4 text-cyan-500" />
            <span>AI score evaluations</span>
          </div>
          <p className="text-3xl font-black text-slate-100 font-display">580+ Startups</p>
        </div>
        <div className="space-y-1">
          <div className="flex items-center justify-center space-x-1.5 text-slate-500 font-bold uppercase tracking-wider text-[11px]">
            <Sparkles className="w-4 h-4 text-amber-500" />
            <span>Average VC Readiness</span>
          </div>
          <p className="text-3xl font-black text-slate-100 font-display">86% Benchmark</p>
        </div>
      </div>
    </div>
  );
}
